AWSTemplateFormatVersion: '2010-09-09'
Resources:
  childBucket:
   Type: AWS::S3::Bucket
   Properties:
    BucketName : amod.kadam.child.bucket
    
  myStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-templates-us-east-1/S3_Bucket.template
      TimeoutInMinutes: '60'

Outputs:
 StackRef:
    Value: !Ref myStack
 OutputFromNestedStack:
    Value: !GetAtt myStack.Outputs.BucketName